import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectRoot = path.resolve(__dirname, '..');
const skillsDir = path.resolve(projectRoot, 'AGF/.skills');
const libraryFile = path.resolve(projectRoot, 'AGF/.skills/skill-library.md');

const categoryMap = {
    'meta-orchestration': '🏗️ Core Architecture & Governance',
    'architecture': '🛠️ System Design & Architecture (New)',
    'engineering': '💻 Software Engineering & Quality',
    'ai': '🧠 AI & Prompt Engineering',
    'design': '🎨 Frontend & Design (Stitch)',
    'default': '🧩 Uncategorized Skills'
};

const getCategoryName = (category) => categoryMap[category] || categoryMap.default;

const skills = [];

// Fallback categorization to preserve current AGF catalog look constraints
const knownCategorizations = {
    'main-skill': 'meta-orchestration',
    'skill-loader': 'meta-orchestration',
    'security-review': 'meta-orchestration',
    'error-reporting': 'meta-orchestration',
    'lessons-learned': 'meta-orchestration',
    'this-project-only-skill': 'meta-orchestration',
    'architect-review': 'architecture',
    'architecture-patterns': 'architecture',
    'architecture-decision-records': 'architecture',
    'backend-architect': 'architecture',
    'database-architect': 'architecture',
    'api-design-principles': 'architecture',
    'backend-dev-guidelines': 'engineering',
    'code-reviewer': 'engineering',
    'code-review-checklist': 'engineering',
    'xlsx-official': 'engineering',
    'llm-prompt-optimizer': 'ai',
    'skill-creator': 'ai',
    'DESIGN': 'design',
    'frontend-architect': 'design',
    'stitch-design': 'design',
    'stitch-design-md': 'design',
    'stitch-enhance-prompt': 'design',
    'stitch-react-components': 'design',
    'stitch-loop': 'design',
    'stitch-remotion': 'design',
    'stitch-shadcn-ui': 'design'
};

if (!fs.existsSync(skillsDir)) {
    console.error('Directory AGF/.skills not found');
    process.exit(1);
}

const entries = fs.readdirSync(skillsDir, { withFileTypes: true });

entries.forEach(entry => {
    if (entry.isDirectory()) {
        const skillMd = path.join(skillsDir, entry.name, 'SKILL.md');
        if (fs.existsSync(skillMd)) {
            const content = fs.readFileSync(skillMd, 'utf8');
            const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
            
            let name = entry.name;
            let description = 'No description available.';
            let category = knownCategorizations[entry.name] || 'default';
            
            if (frontmatterMatch) {
                const lines = frontmatterMatch[1].split('\n');
                lines.forEach(line => {
                    if (line.startsWith('name:')) name = line.replace('name:', '').trim().replace(/"/g, '').replace(/'/g, '');
                    if (line.startsWith('category:')) category = line.replace('category:', '').trim();
                });
                
                // Enhanced description parsing (supports multiline ">" syntax in YAML)
                const metaBlock = frontmatterMatch[1];
                const descSingle = metaBlock.match(/description:\s*(?!>)(.*)/);
                const descMulti = metaBlock.match(/description:\s*>\s*\n((?:\s+.*?\n)+)/);
                
                if (descMulti && descMulti[1]) {
                    description = descMulti[1].replace(/\s+/g, ' ').trim();
                } else if (descSingle && descSingle[1]) {
                    description = descSingle[1].replace(/["']/g, '').trim();
                }
            }
            
            skills.push({ name, description, category });
        }
    }
});

const groupedSkills = skills.reduce((acc, skill) => {
    const catName = getCategoryName(skill.category);
    if (!acc[catName]) acc[catName] = [];
    acc[catName].push(skill);
    return acc;
}, {});

let markdownOutput = `# Skill Library — AGF v2.0
## 🎯 Single Source of Truth for Agent Orchestration

This document is the definitive catalog of the framework's capabilities, integrating architecture, development, security, and design skills.
*(Auto-generated by automation/sync-skills.js)*

---

`;

Object.keys(groupedSkills).forEach(category => {
    markdownOutput += `## ${category}\n`;
    markdownOutput += `| Skill Name | Description |\n|:---|:---|\n`;
    groupedSkills[category].forEach(skill => {
        let safeDesc = skill.description.substring(0, 100);
        if (skill.description.length > 100) safeDesc += '...';
        markdownOutput += `| **${skill.name}** | ${safeDesc} |\n`;
    });
    markdownOutput += `\n`;
});

const today = new Date().toISOString().split('T')[0];
markdownOutput += `---
*Last update: ${today} | Version: 2.0.0*
*"Framework hardened. Skills aligned. Ready for execution."*
`;

fs.writeFileSync(libraryFile, markdownOutput);
console.log('✅ AGF skill-library.md successfully synchronized with filesystem.');
